### PR TITLE
authenticate-with-devise

### PR DESCRIPTION
**Pull request by thanhhungchu95**

### CODE REVIEW

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by thanhhungchu95** [comment]
ready

**Comment by dieunb** [comment]
commented

**Comment by thanhhungchu95** [comment]
ready

**Comment by dieunb** [comment]
commented

**Pull request merged**
